version: '3.3'
services:

  # MYSQLのバージョンと名前の指定
  mysql:
    image: mysql:5.7
    container_name: db-for-go

    # MySQLの設定値を指定する
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # コンテナ内で使用する環境変数の値を指定する
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASS: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'

    # コンテナの3306ポートをローカルの3306ポートにマッピングする
    ports:
      - "13306:3306"

    # コンテナの中にあるMYSQLにアクセスするためのボリュームを指定する
    volumes:
      - db-volume:/var/lib/mysql

    # ボリュームの作成
volumes:
  db-volume:
